// LOGIN PAGE
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

// ORGANIZATION PAGE
export const ADD_ORGANIZATION = "ADD_ORGANIZATION";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
export const CHANGE_ORGANIZATION = "CHANGE_ORGANIZATION";
